apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x1jo8u0ph-go
  janus-idp.io/tekton: x1jo8u0ph-go
  backstage.io/kubernetes-id: x1jo8u0ph-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x1jo8u0ph-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
